# Generated by Django 4.2.23 on 2026-03-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrilleTarifaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcpu_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('ram_mb_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('disk_gb_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grille Tarifaire',
            },
        ),
    ]
