# Generated by Django 4.2.23 on 2026-03-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=64, unique=True)),
                ('budget_mensuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('seuil_alerte', models.IntegerField(default=80, help_text="Seuil d'alerte (%)")),
                ('seuil_blocage', models.IntegerField(default=100, help_text='Seuil de blocage (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget du Projet',
            },
        ),
    ]
